# encabezados para la plantilla
---
name: "Nueva Característica, Modulo, Función"
description: "Sugerencia de una nueva funcionalidad en el módulo de compras"
title: "[Feature]: "
labels: ["feature request"]

# cuerpo de la estructura yml
body:
  - type: markdown
    attributes:
      value: |
        Gracias por tu interés en mejorar la aplicación. Por favor, proporciona la siguiente información para ayudarnos a entender y evaluar tu propuesta.

  - type: textarea
    id: feature-description
    attributes:
      label: "Descripción de la nueva característica, funcion, modulo"
      description: "Descripción clara y concisa de la funcionalidad que estás proponiendo."
      placeholder: "Me gustaría que la aplicación tenga una función de modo oscuro..."
    validations:
      required: true

  - type: dropdown
    id: tipo
    attributes:
      label: "Tipo"
      description: "Selecciona la opción que corresponda a la nueva función."
      options:
        - "Mejora de la funcion existente"
        - "Implemenacion de nueava funcion"
        # - "Funcionalidad existente"
    validations:
      required: true

  # Campo de descripción opcional
  - type: textarea
    id: solution-ideas
    attributes:
      label: "Nuevas funciones para el area "
      description: "Si tienes ideas sobre cómo implementar esta característica, descríbelas aquí."
      placeholder: "Especificar el area de la nueva funcion,o si ya existe que tiene que mejorar..."
    validations:
      required: false
